#!/usr/bin/env python3
""" 3. List all documents in Python
"""
// Lists all documents with name starting by Holberton in the school collection.
db.school.find({name: /Holberton.*/}).forEach(printjson);
